# CMake generated Testfile for 
# Source directory: /Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests
# Build directory: /Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(wtest "/Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests/wtest")
set_tests_properties(wtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;27;add_test;/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;0;")
add_test(rtest "/usr/local/Cellar/cmake/3.23.0/bin/cmake" "-DOUT=/Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests/rtest.out" "-DDATA=/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=/Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests/rtest" "-P" "/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/compare_test.cmake")
set_tests_properties(rtest PROPERTIES  _BACKTRACE_TRIPLES "/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;18;add_test;/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;28;add_compare_test;/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;0;")
add_test(ftest "/usr/local/Cellar/cmake/3.23.0/bin/cmake" "-DOUT=/Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests/ftest.out" "-DDATA=/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=/Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests/ftest" "-P" "/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/compare_test.cmake")
set_tests_properties(ftest PROPERTIES  _BACKTRACE_TRIPLES "/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;18;add_test;/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;29;add_compare_test;/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;0;")
add_test(halftest "/Users/corneria/Documents/Research/bias_research/pbrttest/ImageEditLib/src/ext/ptex/src/tests/halftest")
set_tests_properties(halftest PROPERTIES  _BACKTRACE_TRIPLES "/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;30;add_test;/Users/corneria/Documents/Research/bias_research/pbrttest/src/ext/ptex/src/tests/CMakeLists.txt;0;")
