#pragma once

#include <conver/techniques/blanchet/bin_blanchet_add.h>
#include <conver/techniques/blanchet/bin_blanchet_fast.h>
#include <conver/techniques/blanchet/bin_blanchet_if.h>
#include <conver/techniques/blanchet/bin_blanchet.h>
#include <conver/techniques/blanchet/bin_blanchet_final.h>
#include <conver/techniques/blanchet/blanchet_adaptive_opt.h>
#include <conver/techniques/blanchet/blanchet_adaptive.h>
#include <conver/techniques/blanchet/blanchet_basic.h>
#include <conver/techniques/blanchet/blanchet_cmf.h>
#include <conver/techniques/blanchet/blanchet_corfirst.h>
#include <conver/techniques/blanchet/blanchet_final.h>
#include <conver/techniques/blanchet/blanchet_naive.h>
#include <conver/techniques/blanchet/blanchet_normal.h>
#include <conver/techniques/blanchet/blanchet_ray_rot.h>
#include <conver/techniques/blanchet/blanchet_ray.h>
#include <conver/techniques/blanchet/blanchet_taylor.h>
#include <conver/techniques/blanchet/blanchet.h>
#include <conver/techniques/exp/exp_pcume.h>
#include <conver/techniques/exp/exp_pcmf.h>
#include <conver/techniques/exp/exp_pcmf_mod.h>
#include <conver/techniques/exp/exp_pratio.h>
#include <conver/techniques/exp/exp_ratio.h>
#include <conver/techniques/exp/exp_iterative_ratio.h>
#include <conver/techniques/exp/exp_delta.h>
#include <conver/techniques/exp/exp_delta_weighted.h>
#include <conver/techniques/exp/exp_adaptive_delta.h>
#include <conver/techniques/exp/exp_adaptive_ratio.h>
#include <conver/techniques/exp/exp_adaptive_ratio_full.h>
#include <conver/techniques/exp/exp_adaptive_ratio_avg.h>
#include <conver/techniques/exp/exp_adaptive_ratio_clamp.h>
#include <conver/techniques/exp/exp_adaptive_ratio_avg_clamp.h>
#include <conver/techniques/exp/exp_adaptive_delta_full.h>
#include <conver/techniques/exp/exp_adaptive_ratio_mult.h>
#include <conver/techniques/exp/exp_adaptive_ratio_both.h>
#include <conver/techniques/exp/exp_adaptive_all_dumb.h>
#include <conver/techniques/exp/exp_adaptive_double.h>
#include <conver/techniques/exp/exp_adaptive_max.h>
#include <conver/techniques/exp/exp_adaptive_max_nf.h>
#include <conver/techniques/exp/exp_nvidia.h>
#include <conver/techniques/exp/exp_ray.h>
#include <conver/techniques/exp/exp_ray_adapratstep.h>
#include <conver/techniques/exp/exp_ray_ratstep.h>
#include <conver/techniques/exp/exp_ray_naive_var.h>
#include <conver/techniques/exp/exp_ray_prog_var.h>
#include <conver/techniques/exp/exp_noncor_ray.h>
#include <conver/techniques/exp/exp_noncor_ray_adapratstep.h>
#include <conver/techniques/exp/exp_noncor_ray_ratstep.h>
#include <conver/techniques/exp/exp_noncor_ray_naive_var.h>
#include <conver/techniques/exp/exp_noncor_ray_prog_var.h>
#include <conver/techniques/tele_cor.h>
#include <conver/techniques/tele_naive.h>
#include <conver/techniques/tele_naive_bounds.h>

// TODO: also need to prune out all of the extranuous blanchet estimators
